/*
 * File: exer6com.cpp
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Fri Jan 30 20:27:03 2026
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                exer6com

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     1

/* Input Port  0 */
#define IN_PORT_0_NAME                 u0
#define INPUT_0_DIMS_ND                {1,1}
#define INPUT_0_NUM_ELEMS              1
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  1
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            3
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125
#define NUM_OUTPUTS                    2

/* Output Port  0 */
#define OUT_PORT_0_NAME                y0
#define OUTPUT_0_DIMS_ND               {1,1}
#define OUTPUT_0_NUM_ELEMS             1
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                y1
#define OUTPUT_1_DIMS_ND               {1,1}
#define OUTPUT_1_NUM_ELEMS             1
#define OUTPUT_1_WIDTH                 1
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 real_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUTPUT_1_UNIT                  ""
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     1-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125
#define NPARAMS                        5

/* Parameter 0 */
#define PARAMETER_0_NAME               L
#define PARAMETER_0_DTYPE              real_T
#define PARAMETER_0_COMPLEX            COMPLEX_NO
#define PARAMETER_0_UNIT               ""

/* Parameter 1 */
#define PARAMETER_1_NAME               cm
#define PARAMETER_1_DTYPE              real_T
#define PARAMETER_1_COMPLEX            COMPLEX_NO
#define PARAMETER_1_UNIT               ""

/* Parameter 2 */
#define PARAMETER_2_NAME               J
#define PARAMETER_2_DTYPE              real_T
#define PARAMETER_2_COMPLEX            COMPLEX_NO
#define PARAMETER_2_UNIT               ""

/* Parameter 3 */
#define PARAMETER_3_NAME               R
#define PARAMETER_3_DTYPE              real_T
#define PARAMETER_3_COMPLEX            COMPLEX_NO
#define PARAMETER_3_UNIT               ""

/* Parameter 4 */
#define PARAMETER_4_NAME               D
#define PARAMETER_4_DTYPE              real_T
#define PARAMETER_4_COMPLEX            COMPLEX_NO
#define PARAMETER_4_UNIT               ""
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                2
#define CONT_STATES_IC                 [0,0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S)                  ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S)                  ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S)                  ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S)                  ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S)                  ssGetSFcnParam(S, 4)
#define IS_PARAM_DOUBLE(pVal)          (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

extern "C" void exer6com_Outputs_wrapper(const real_T *u0,
  real_T *y0,
  real_T *y1,
  const real_T *xC,
  const real_T *L, const int_T p_width0,
  const real_T *cm, const int_T p_width1,
  const real_T *J, const int_T p_width2,
  const real_T *R, const int_T p_width3,
  const real_T *D, const int_T p_width4);
extern "C" void exer6com_Derivatives_wrapper(const real_T *u0,
  real_T *y0,
  real_T *y1,
  real_T *dx,
  real_T *xC,
  const real_T *L, const int_T p_width0,
  const real_T *cm, const int_T p_width1,
  const real_T *J, const int_T p_width2,
  const real_T *R, const int_T p_width3,
  const real_T *D, const int_T p_width4);

/*====================*
 * S-function methods *
 *====================*/
#if !defined(__LCC__) && (defined(__cplusplus) || (__STDC_VERSION__ >= 199901L))
#define __sfb_snprintf_(msgToWriteTo,size,fmtStr,arg1) snprintf(msgToWriteTo,size,fmtStr,arg1)
#else
#define __sfb_snprintf_(msgToWriteTo,size,fmtStr,arg1) sprintf(msgToWriteTo,fmtStr,arg1)
#endif

#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)

/* Function: mdlCheckParameters =============================================
 * Abstract:
 *     Verify parameter definitions and types.
 */
static void mdlCheckParameters(SimStruct *S)
{
  int paramIndex = 0;
  bool invalidParam = false;

  /* All parameters must match the Code Builder Dialog */
  {
    const mxArray *pVal0 = ssGetSFcnParam(S, 0);
    if (!IS_PARAM_DOUBLE(pVal0)) {
      invalidParam = true;
      paramIndex = 0;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal1 = ssGetSFcnParam(S, 1);
    if (!IS_PARAM_DOUBLE(pVal1)) {
      invalidParam = true;
      paramIndex = 1;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal2 = ssGetSFcnParam(S, 2);
    if (!IS_PARAM_DOUBLE(pVal2)) {
      invalidParam = true;
      paramIndex = 2;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal3 = ssGetSFcnParam(S, 3);
    if (!IS_PARAM_DOUBLE(pVal3)) {
      invalidParam = true;
      paramIndex = 3;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal4 = ssGetSFcnParam(S, 4);
    if (!IS_PARAM_DOUBLE(pVal4)) {
      invalidParam = true;
      paramIndex = 4;
      goto EXIT_POINT;
    }
  }

 EXIT_POINT:
  if (invalidParam) {
    static char parameterErrorMsg[1024];
    __sfb_snprintf_(parameterErrorMsg, 1024,
                    "The data type and or complexity of parameter %d does not match the "
                    "information specified in the Code Builder dialog. "
                    "For non-double parameters you will need to cast them using int8, int16, "
                    "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
    ssSetLocalErrorStatus(S, parameterErrorMsg);
  }

  return;
}

#endif                                 /* MDL_CHECK_PARAMETERS */

/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  ssSetNumSFcnParams(S, NPARAMS);      /* Number of expected parameters */

#if defined(MATLAB_MEX_FILE)

  if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
    mdlCheckParameters(S);
    if (ssGetErrorStatus(S) != NULL) {
      return;
    }
  } else {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  UnitId pUnitIdReg;
  ssRegisterUnitFromExpr(S, PARAMETER_0_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 0, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

  ssRegisterUnitFromExpr(S, PARAMETER_1_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 1, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

  ssRegisterUnitFromExpr(S, PARAMETER_2_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 2, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

  ssRegisterUnitFromExpr(S, PARAMETER_3_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 3, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

  ssRegisterUnitFromExpr(S, PARAMETER_4_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 4, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

#endif

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port u0 of S-Function exer6com");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_NUM_ELEMS);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  ssSetOutputPortWidth(S, 1, OUTPUT_1_NUM_ELEMS);
  ssSetOutputPortDataType(S, 1, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port y0 of S-Function exer6com");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_1_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 1, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port y1 of S-Function exer6com");
      return;
    }

#endif

  }

  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "25.2");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_INITIALIZE_CONDITIONS

/* Function: mdlInitializeConditions ========================================
 * Abstract:
 *    Initialize the states
 */
static void mdlInitializeConditions(SimStruct *S)
{
  real_T *xC = ssGetContStates(S);
  xC[0] = 0;
  xC[1] = 0;
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
  const char_T *rtParamNames[] = { "P1", "P2", "P3", "P4", "P5" };

  ssRegAllTunableParamsAsRunTimeParams(S, rtParamNames);
}

#endif

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const real_T *u0 = (real_T *) ssGetInputPortRealSignal(S, 0);
  real_T *y0 = (real_T *) ssGetOutputPortRealSignal(S, 0);
  real_T *y1 = (real_T *) ssGetOutputPortRealSignal(S, 1);
  const real_T *xC = ssGetContStates(S);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const int_T p_width3 = mxGetNumberOfElements(PARAM_DEF3(S));
  const int_T p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
  const real_T *L = (const real_T *) mxGetDoubles(PARAM_DEF0(S));
  const real_T *cm = (const real_T *) mxGetDoubles(PARAM_DEF1(S));
  const real_T *J = (const real_T *) mxGetDoubles(PARAM_DEF2(S));
  const real_T *R = (const real_T *) mxGetDoubles(PARAM_DEF3(S));
  const real_T *D = (const real_T *) mxGetDoubles(PARAM_DEF4(S));
  exer6com_Outputs_wrapper(u0, y0, y1, xC, L, p_width0, cm, p_width1, J,
    p_width2, R, p_width3, D, p_width4);
}

#define MDL_DERIVATIVES                                          /* Change to #undef to remove function */
#if defined(MDL_DERIVATIVES)

/* Function: mdlDerivatives =================================================
 * Abstract:
 *    In this function, you compute the S-function block's derivatives.
 *    The derivatives are placed in the derivative vector, ssGetdX(S).
 */
static void mdlDerivatives(SimStruct *S)
{
  const real_T *u0 = (real_T *) ssGetInputPortRealSignal(S, 0);
  real_T *y0 = (real_T *) ssGetOutputPortRealSignal(S, 0);
  real_T *y1 = (real_T *) ssGetOutputPortRealSignal(S, 1);
  real_T *dx = ssGetdX(S);
  real_T *xC = ssGetContStates(S);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const int_T p_width3 = mxGetNumberOfElements(PARAM_DEF3(S));
  const int_T p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
  const real_T *L = (const real_T *) mxGetDoubles(PARAM_DEF0(S));
  const real_T *cm = (const real_T *) mxGetDoubles(PARAM_DEF1(S));
  const real_T *J = (const real_T *) mxGetDoubles(PARAM_DEF2(S));
  const real_T *R = (const real_T *) mxGetDoubles(PARAM_DEF3(S));
  const real_T *D = (const real_T *) mxGetDoubles(PARAM_DEF4(S));
  exer6com_Derivatives_wrapper(u0, y0, y1, dx, xC, L, p_width0, cm, p_width1, J,
    p_width2, R, p_width3, D, p_width4);
}

#endif                                 /* MDL_DERIVATIVES */

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
